<?php namespace ForeverPHP\Session;

// ESTA CLASE MANEJA LAS SESIONES DE USUARIO Y HERADA MODEL SE USA PARA SESIONES DE USUARIO PROPIAS DEL FRAMEWORK.
class UserModel extends \ForeverPHP\Database\Model {

}
